modLoader="javafml"
loaderVersion="[40,)"
license="MIT License"
issueTrackerURL="https://github.com/damoc1es/vertigoes/issues"

[[mods]]
modId="vertigoes"
version="${file.jarVersion}"
displayName="Vertigoes"
displayURL="https://vertigoes.damocles.dev/"
logoFile="logo.png"
authors="damoc1es"
description='''
Vertigoes is a small Forge Minecraft mod that adds some small random things I've thought about..
Have fun!
'''

[[dependencies.vertigoes]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.vertigoes]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
